### ISSUE TITLE
Hardware Authenticators not compatible with KvStore

### ISSUE THREAD

**Issue by fmorency** [liftedinit/gwen#42]
One can create/import a hardware authenticator MANY identity when using a kvstore backend. The application should not display the option to the user as the kvstore backend does not currently support hardware authenticator.

![2023-03-28_14-04](https://user-images.githubusercontent.com/1102868/228328575-0ec2df84-2d5d-4194-9c83-ea423cbfc373.png)
![2023-03-28_14-06](https://user-images.githubusercontent.com/1102868/228328707-c4e51862-0f6c-4a0f-865b-7b64c964d74c.png)

**Comment by stanleyjones** [comment]
@fmorency Was this issue resolved by the redesign that only shows Services that are available for the chosen Neighborhood?

**Comment by stanleyjones** [comment]
@fmorency Question on implementation here...

Technically, we don't need to communicate with the `idStore` once the identity has been created and/or retrieved. Should we:

1. Disable the "Hardware Authenticator" creation/import option if the selected neighborhood doesn't support `idStore` but still allow the user to use a previously created/imported identity on a non-idStore neighborhood.
2. Fall back to a neighborhood that _does_ support `idStore` if the selected neighborhood doesn't (i.e. create/import the ID on the Manifest Ledger unless otherwise specified).
3. Disable Hardware Authenticator based identities _completely_ (i.e. require the user to select a different identity) if the selected neighborhood doesn't support `idStore`.

Those are in rough order of my preference.
